version: "3.7"
services:
  caddy:
    image: apples723/awslab-flask-app:v0.3
    container_name: awslab-flask
    ports:
      - 8000:8000
    restart: always
networks:
  default:
    external:
      name: caddy