version: "3.7"
services:
  flask-app:
    image: apples723/awslab-flask-app:v1.3.0-amd64
    container_name: awslab-flask
    ports:
      - 443:443
    restart: always
networks:
  default:
    external:
      name: caddy