version: "3.7"
services:
  flask-app:
    image: apples723/awslab-flask-app:v1.2.0
    container_name: awslab-flask
    ports:
      - 8000:8000
    restart: always
networks:
  default:
    external:
      name: caddy